Added "Note Screen" And "Add Note Screen"
gdsc-jssstu/student_study_manager pull request #13
Opened 2022-10-16 02:55 UTC by UtkarshDeoli

files #3

2022-10-16 03:41 UTC, UtkarshDeoli commented
https://user-images.githubusercontent.com/89682101/196016809-d8571bb9-733c-4743-81c4-da842726ac18.mp4
This is the preview of the UI

2022-10-16 12:08 UTC, ShivamMenda requested changes
@UtkarshDeoli I've reviewed your code and the UI looks good, there are some small changes I've suggested please go through that and make the necessary changes.

2022-10-16 12:08 UTC, ShivamMenda commented on lib/widgets/notes_screen_container.dart
> +  String title;
As this field isn't final it would mark it as @immutable. Add the final keyword here.

2022-10-16 12:08 UTC, ShivamMenda commented on lib/widgets/notes_screen_container.dart
> +  NoteScreenCont({super.key, required this.title});
Make this const once the field has been marked final.

2022-10-16 12:08 UTC, ShivamMenda commented on lib/screens/study_materials_screen.dart
Use a key here to define your class constructor(Always a good practice)

2022-10-16 12:34 UTC, UtkarshDeoli commented
ok, sure @ShivamMenda

2022-10-17 02:41 UTC, ShivamMenda approved these changes
Everything Looks good @UtkarshDeoli! Good Work!

2022-10-17 02:42 UTC, merged