Updated UI
gdsc-jssstu/student_study_manager pull request #15
Opened 2022-10-21 16:30 UTC by mufida1018

Hey,
Pls check

2022-10-26 07:07 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
>  class RemaindersScreen extends StatelessWidget {
Add a key here. Always use key in widget constructors.

2022-10-26 07:08 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +        iconTheme: IconThemeData(
Add const here.

2022-10-26 07:09 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +        title: Text("Remainder\'s",style: TextStyle(color: Colors.black,fontWeight: FontWeight.bold),),
Add const here.

2022-10-26 07:09 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +        actions: [
Add const here

2022-10-26 07:10 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                           Text("Title"),
Add const here

2022-10-26 07:10 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                           Text("Para"),
Add const here too

2022-10-26 07:11 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                           SizedBox(height: 3,),
Add const and increase a little height.

2022-10-26 07:11 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                               Text("TODAY"),
Add const here

2022-10-26 07:11 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                               Text("6:00 PM"),
Add const here too

2022-10-26 07:12 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +            Text("UPCOMING",style:TextStyle(fontWeight: FontWeight.bold)),
Add const and make title italic.

2022-10-26 07:12 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                               Text("TODAY"),
Make this italic too

2022-10-26 07:13 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                            Text("TODAY"),
Add const and make italic

2022-10-26 07:13 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +                            Text("6:00 PM"),
Add const and make italic

2022-10-26 07:14 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +          SizedBox(height: 18,),
Add const

2022-10-26 07:14 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +            "+",
Add const

2022-10-26 07:14 UTC, ShivamMenda commented on lib/screens/remainders_screen.dart
> +            style: TextStyle(color: Colors.black, fontSize: 35, fontWeight: FontWeight.bold),
Add const

2022-10-26 07:17 UTC, ShivamMenda requested changes
@mufida1018 I've suggested some code quality changes. Please do make them. Also please follow the spacing and italics as given in the UI in the readme file. The Today and upcoming title is sticking to the screen. Give some padding there and make text italic wherever necessary.

2022-10-30 07:19 UTC, mufida1018 commented
Pls check

2022-10-30 07:22 UTC, ShivamMenda commented
@mufida1018 will check and get back to you.

2022-10-30 11:38 UTC, ShivamMenda approved these changes
Looks good! Thank you for your contribution!

2022-10-30 11:39 UTC, merged